import {useEffect,useState} from 'react';
import {Search,ExternalLink,FileText,BookOpen,ArrowRight,Database,ShieldCheck,RefreshCw} from 'lucide-react';
function MediaShelf({status}){
 const [type,setType]=useState(''),[page,setPage]=useState(1),[data,setData]=useState({items:[],total:0});
 useEffect(()=>{let live=true;fetch(`/api/archive/media?page=${page}&type=${encodeURIComponent(type)}`).then(r=>r.json()).then(value=>{if(live)setData(value)}).catch(()=>{});return()=>{live=false};},[type,page,status?.mediaSaved]);
 return <section className="media-shelf"><div className="result-header"><div><span className="section-kicker">SALINAN SETEMPAT</span><h3>Media Arkib Negara</h3></div><span>{status?.mediaSaved||0} fail disimpan · {status?.mediaPending||0} menunggu</span></div><div className="media-filters">{['','ebook / dokumen','imej','audio','video','fail'].map(value=><button key={value} className={type===value?'active':''} onClick={()=>{setType(value);setPage(1)}}>{value||'Semua'}</button>)}</div><div className="media-grid">{data.items.map(item=><a key={item.id} className="media-item" href={item.localUrl} target="_blank" rel="noreferrer" title={item.name}>{item.category==='imej'?<img src={item.localUrl} alt={item.name}/>:<FileText size={24}/>}<span>{item.name}</span><small>{Math.round(item.bytes/1024).toLocaleString('ms-MY')} KB</small></a>)}</div>{!data.items.length&&<p className="media-empty">Media awam sedang dimuat turun ke storan setempat.</p>}{data.total>24&&<div className="pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><span>Halaman {page} / {Math.ceil(data.total/24)}</span><button disabled={page*24>=data.total} onClick={()=>setPage(p=>p+1)}>Seterusnya</button></div>}</section>;
}
export default function ArchivePage({ask,navigate}){
 const [status,setStatus]=useState(null),[query,setQuery]=useState(''),[searched,setSearched]=useState(''),[documents,setDocuments]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false),[page,setPage]=useState(1),[total,setTotal]=useState(0);
 useEffect(()=>{let live=true;const update=async()=>{try{const r=await fetch('/api/archive/status');if(live&&r.ok)setStatus(await r.json());}catch{}};update();const id=setInterval(update,20000);return()=>{live=false;clearInterval(id);};},[]);
 useEffect(()=>{let live=true;setLoading(true);const url=searched?`/api/archive/documents?q=${encodeURIComponent(searched)}`:`/api/archive/documents?page=${page}`;fetch(url).then(r=>r.json()).then(data=>{if(live){setDocuments(data.documents||[]);setTotal(data.total||0);setSelected(null);}}).catch(()=>{}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[searched,page,status?.documents]);
 const find=e=>{e.preventDefault();setPage(1);setSearched(query.trim());};
 return <div className="archive-page content-container">
  <div className="intro-grid"><div><span className="section-kicker">CARIAN SUMBER RASMI</span><h2>Terokai rekod. Semak sumber.</h2><p>Cari bahan awam yang diimport daripada laman Arkib Negara Malaysia. AIMAN memetik sumber yang digunakan dan enggan membuat dakwaan arkib tanpa bukti.</p></div><div className="coverage-card"><Database size={18}/><div><strong>{status?.documents?.toLocaleString('ms-MY')||'0'}</strong><span>dokumen atau halaman diindeks</span></div><small>{status?.status==='running'?'Pengimportan sedang berjalan':status?.status==='complete'?'Pengimportan selesai':'Indeks belum lengkap'} · {status?.pagesVisited||0} halaman diperiksa · {status?.pending||0} belum diproses</small></div></div>
  <form className="search-form" onSubmit={find}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari koleksi, peristiwa, tokoh atau kata kunci…" aria-label="Cari rekod Arkib Negara"/><button type="submit" className="btn primary">Cari rekod <ArrowRight size={16}/></button></form>
  <div className="research-guide"><ShieldCheck size={18}/><span>Jawapan AIMAN memerlukan petikan yang dapat disemak. Hasil carian ini hanya merangkumi bahan awam yang telah berjaya diimport.</span><button onClick={()=>navigate('jawi')}>Analisis Jawi <ArrowRight size={14}/></button></div>
  <div className="result-header"><div><span className="section-kicker">KOLEKSI YANG DIINDEKS</span><h3>{searched?`Hasil untuk “${searched}”`:'Rekod terkini'}</h3></div>{searched&&<button className="plain-link" onClick={()=>{setQuery('');setSearched('');}}>Kosongkan carian</button>}</div>
  <div className="archive-columns"><div className="result-list">{loading&&<div className="empty-card"><RefreshCw size={18}/>Memuatkan rekod…</div>}{!loading&&!documents.length&&<div className="empty-card"><BookOpen size={26}/><strong>Tiada rekod ditemui.</strong><p>Cuba kata kunci lain atau tunggu pengimportan bahan awam.</p></div>}{!loading&&documents.map((d,i)=><button key={d.id||i} className={'record-row '+(selected?.id===d.id?'selected':'')} onClick={()=>setSelected(d)}><span className="record-icon"><FileText size={19}/></span><span className="record-content"><small>{d.type==='pdf'?`PDF · HALAMAN ${d.page}`:'HALAMAN WEB'} · ARKIB NEGARA MALAYSIA</small><strong>{d.title}</strong><em>{d.text?.replace(/\s+/g,' ').slice(0,210)}</em></span><ArrowRight size={16}/></button>)}{!searched&&total>12&&<div className="pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><span>Halaman {page} / {Math.ceil(total/12)}</span><button disabled={page*12>=total} onClick={()=>setPage(p=>p+1)}>Seterusnya</button></div>}</div><aside className="source-preview">{selected?<><span className="section-kicker">PRATONTON SUMBER</span><h3>{selected.title}</h3><div className="source-meta"><span>{selected.publisher||'Arkib Negara Malaysia'}</span>{selected.page&&<span>Halaman {selected.page}</span>}</div><blockquote>{selected.text?.slice(0,2000)}</blockquote>{selected.url?<a href={selected.url} target="_blank" rel="noreferrer" className="btn secondary">Buka salinan setempat <ExternalLink size={15}/></a>:<p>Salinan media ini masih dimuat turun.</p>}<button onClick={()=>ask(`Apakah yang dapat dibuktikan tentang ${selected.title}?`)} className="btn primary">Tanya AIMAN tentang rekod ini <ArrowRight size={16}/></button></>:<><div className="preview-icon"><BookOpen size={26}/></div><h3>Semak rekod di sini</h3><p>Pilih rekod di sebelah kiri untuk melihat petikan dan butiran sumber setempat.</p></>}</aside></div>
  <MediaShelf status={status}/>
  <div className="coverage-footnote"><strong>Skop indeks:</strong> {status?.scope||'Import halaman awam laman Arkib Negara Malaysia.'} {status?.failures>0&&`${status.failures} URL gagal diambil.`} Sumber luar, rekod tertutup dan dokumen imbasan tanpa teks mungkin belum tersedia.</div>
 </div>;
}
