import {useEffect,useRef,useState,useCallback} from 'react';
import {ArrowUp,Mic,MicOff,Minus,Volume2,VolumeX,Square,Settings,Hand,ArrowUpFromLine,Check,RotateCcw,ExternalLink,MessageSquare,ChevronDown} from 'lucide-react';
import Robot from './Robot';
export default function Assistant({ai,open,setOpen}){
 const [input,setInput]=useState(''),[settings,setSettings]=useState(false),[clips,setClips]=useState([]);const bottom=useRef();
 const loaded=useCallback(names=>setClips(names),[]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[ai.messages,ai.partial,ai.mode]);
 const state=ai.mode==='thinking'?'Menyemak sumber…':ai.mode==='preparing'?'Menyediakan suara…':ai.mode==='speaking'?'Sedang bercakap':ai.micPending?'Menunggu ASR sedia':ai.mic?'Sedang mendengar':'Pembantu penyelidikan anda';
 return <div className={`aiman-dock ${open?'is-open':''}`}>
  {open&&<section className="assistant-panel" aria-label="Sembang AIMAN"><header className="assistant-header"><div><strong>AIMAN&nbsp;</strong><small>{state}</small></div><button aria-label="Tetapan AIMAN" onClick={()=>setSettings(v=>!v)}><Settings size={17} aria-hidden="true"/></button><button aria-label="Kecilkan AIMAN" onClick={()=>setOpen(false)}><Minus size={19} aria-hidden="true"/></button></header>
   {settings?<div className="assistant-settings"><h3>Sambungan tempatan</h3>{[['asr','Pengecaman suara'],['chat','Model bahasa'],['tts','Penjanaan suara'],['vision','Jawi & tulisan tangan']].map(([key,label])=><div key={key}><span>{label}: </span><b className={ai.health.services[key]?'online':'offline'}>{ai.health.states?.[key]==='busy'?'Sedang menjana suara':ai.health.services[key]?'Tersedia':'Tidak aktif'}</b></div>)}<button className="btn secondary" onClick={ai.refresh}><RotateCcw size={14} aria-hidden="true"/>Semak semula</button><p>ASR dan model bahasa menggunakan Qwen melalui vLLM. Suara Bahasa Melayu menggunakan Chatterbox, manakala Jawi bercetak dibaca dengan Kraken OCR secara setempat. Status menunjukkan servis yang benar-benar sedia.</p></div>:<div className="assistant-messages" aria-live="polite">
    {!ai.messages.length&&<div className="assistant-welcome"><h3>Salam, saya AIMAN.</h3><p>AIMAN membantu penyelidikan anda dengan bukti arkib, membaca Jawi dan menyediakan draf aduan.</p>{['Apa yang berlaku semasa Darurat Tanah Melayu pada tahun 1948?','Saya nak buat aduan','Buka ruang Jawi'].map(t=><button key={t} onClick={()=>ai.send(t)}>{t}<ArrowUp size={13} aria-hidden="true"/></button>)}</div>}
    {ai.messages.map((m,i)=><article key={i} className={'bubble '+m.role}><small>{m.role==='user'?'ANDA':'AIMAN'}</small><p>{m.text}</p>{m.sources?.length>0&&<details open><summary>Sumber digunakan ({m.sources.length})</summary><ul>{m.sources.map((s,index)=><li key={s.id+'-'+index}>{s.url?<a href={s.url} target="_blank" rel="noreferrer">[{s.number}] {s.title}<ExternalLink size={11} aria-hidden="true"/></a>:<span>[{s.number}] {s.title} · salinan sedang dimuat turun</span>}</li>)}</ul></details>}</article>)}
    {ai.partial&&<p className="partial">{ai.partial}</p>}{ai.mode==='thinking'&&<p className="thinking">Mencari petikan yang menyokong soalan…</p>}<div ref={bottom}/>
   </div>}
   {ai.error&&<div className="notice error" role="alert">{ai.error}</div>}
   <form className="assistant-composer" onSubmit={e=>{e.preventDefault();if(input.trim()){ai.send(input);setInput('');}}}><input aria-label="Mesej kepada AIMAN" placeholder="Tanya atau minta bantuan…" maxLength={4000} value={input} onChange={e=>setInput(e.target.value)} disabled={ai.mode!=='idle'}/><button type="button" title="Mikrofon" aria-label={ai.mic?'Hentikan mikrofon':ai.micPending?'Batal menunggu ASR':'Bercakap dengan AIMAN'} className={ai.mic?'recording':''} onClick={()=>ai.toggleMic()}>{ai.mic||ai.micPending?<MicOff size={18} aria-hidden="true"/>:<Mic size={18} aria-hidden="true"/>}</button>{ai.mode==='idle'?<button type="submit" className="send" aria-label="Hantar mesej" disabled={!input.trim()}><ArrowUp size={18} aria-hidden="true"/></button>:<button type="button" className="send" aria-label="Hentikan respons" onClick={ai.stop}><Square size={14} aria-hidden="true"/></button>}</form>
   <div className="assistant-tools"><button onClick={()=>ai.setVoice(v=>!v)} disabled={!ai.health.services.tts} aria-label={!ai.health.services.tts?'Penjanaan suara tidak aktif':ai.voice?'Matikan suara':'Hidupkan suara'}>{ai.voice&&ai.health.services.tts?<Volume2 size={14} aria-hidden="true"/>:<VolumeX size={14} aria-hidden="true"/>}<span>{!ai.health.services.tts?'Suara tidak aktif':ai.voice?'Suara aktif':'Suara dimatikan'}</span></button><div>{[['Wave',Hand,'Lambai'],['Jump',ArrowUpFromLine,'Lompat'],['Nod',Check,'Angguk'],['HeadShake',RotateCcw,'Geleng'],['Blink',ChevronDown,'Kelip']].map(([name,Icon,title])=><button key={name} disabled={!clips.includes(name)} title={title} aria-label={title} onClick={()=>ai.animate(name)}><Icon size={14} aria-hidden="true"/></button>)}</div></div>
  </section>}
  <div className="aiman-launcher"><div className="mini-robot" aria-label="Model AIMAN 3D"><Robot gesture={ai.gesture} player={ai.player} speaking={ai.mode==='speaking'} onLoaded={loaded} resetKey={0}/></div><button onClick={()=>{setOpen(v=>!v);if(!open)ai.animate('Wave');}} aria-expanded={open} className="launcher-label"><MessageSquare size={16} aria-hidden="true"/>{open?'Tutup sembang':'Tanya AIMAN'}<span className={'status-dot '+(ai.health.services.chat?'online':'')}/></button></div>
 </div>;
}
