import {useEffect,useRef,useState} from 'react';
import {Upload,FileImage,ScanSearch,AlertTriangle,ArrowRight,ZoomIn} from 'lucide-react';
export default function JawiPage(){
 const [image,setImage]=useState(''),[name,setName]=useState(''),[result,setResult]=useState(null),[hover,setHover]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[pdfPage,setPdfPage]=useState(0),[pdfCount,setPdfCount]=useState(0);const input=useRef(),pdfRef=useRef(null);
  useEffect(()=>()=>{if(image)URL.revokeObjectURL(image);},[image]);
  const renderPage=async number=>{const pdf=pdfRef.current;if(!pdf)return;setLoading(true);setError('');try{const page=await pdf.getPage(number);const viewport=page.getViewport({scale:1});const scale=Math.min(2,2200/Math.max(viewport.width,viewport.height));const final=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(final.width);canvas.height=Math.ceil(final.height);await page.render({canvasContext:canvas.getContext('2d'),viewport:final}).promise;const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('Halaman PDF tidak dapat dipaparkan.');setImage(URL.createObjectURL(blob));setPdfPage(number);setResult(null);setHover([]);}catch(e){setError(e.message);}finally{setLoading(false);}};
  const pick=async file=>{if(!file)return;setError('');setResult(null);setHover([]);setName(file.name);if(file.type==='application/pdf'){
   if(file.size>25*1024*1024){setError('PDF melebihi 25 MB.');return;}
   try{const {getDocument,GlobalWorkerOptions}=await import('pdfjs-dist/legacy/build/pdf.mjs');GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();const task=getDocument({data:new Uint8Array(await file.arrayBuffer())});pdfRef.current=await task.promise;setPdfCount(pdfRef.current.numPages);await renderPage(1);}catch(e){setError('PDF tidak dapat dibuka: '+e.message);}return;
  }
  pdfRef.current=null;setPdfCount(0);setPdfPage(0);
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('Pilih PNG, JPG, WebP atau PDF di bawah had saiz.');return;}setImage(URL.createObjectURL(file));};
 const analyse=async()=>{if(!image)return;setLoading(true);setError('');try{const blob=await(await fetch(image)).blob();const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});const response=await fetch('/api/handwriting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:encoded})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Pengecaman gagal.');setResult(data);}catch(e){setError(e.message);}finally{setLoading(false);}};
 const hoverIds=ids=>setHover(ids||[]);
 const lines=items=>items.reduce((groups,item)=>{const line=item.line??0;(groups[line]??=[]).push(item);return groups;},[]);
 const verified=result?.segments?.filter(segment=>segment.rumi&&segment.bm&&segment.en).length||0;
 const lowCoverage=Boolean(result?.segments?.length&&verified/result.segments.length<.45);
 const content=kind=>lowCoverage?<p className="ocr-coverage-note">Padanan {kind==='en'?'English':kind==='bm'?'BM':'Rumi'} belum cukup yakin untuk dokumen ini. Semak transkripsi Jawi bersama imej asal.</p>:lines(result?.segments||[]).map((items,line)=>{
  const translation=kind==='en'?result?.lineTranslations?.find(item=>item.line===line):null;
  const pieces=translation?[translation]:items;
  return <div className="transcription-line" key={line}>{pieces?.map((s,i)=><span key={i} tabIndex={0} onMouseEnter={()=>hoverIds(s.wordIds)} onMouseLeave={()=>hoverIds([])} onFocus={()=>hoverIds(s.wordIds)} onBlur={()=>hoverIds([])} title={s[kind]?'Tuding untuk melihat sumber pada imej':'Padanan belum disahkan; semak imej asal'} className={'aligned-segment '+(s[kind]?'':'unverified ')+(s.wordIds.some(id=>hover.includes(id))?'active':'')}>{s[kind]||'Belum disahkan'}{' '}</span>)}</div>;
 });
 const original=()=>lines(result?.words||[]).map((items,line)=><div className="transcription-line" key={line}>{items?.map(w=><span key={w.id} tabIndex={0} onMouseEnter={()=>hoverIds([w.id])} onMouseLeave={()=>hoverIds([])} onFocus={()=>hoverIds([w.id])} onBlur={()=>hoverIds([])} title={w.confidence<.8?'Bacaan OCR kurang pasti; semak imej asal':undefined} className={(hover.includes(w.id)?'active ':'')+(w.confidence<.8?'low-confidence':'')}>{w.text}{' '}</span>)}</div>);
 return <div className="jawi-page content-container"><div className="intro-grid"><div><span className="section-kicker">KECERDASAN DOKUMEN</span><h2>Jawi & tulisan tangan lama</h2><p>Bandingkan imej asal dengan bacaan Jawi bercetak yang perlu disemak. Padanan Rumi, BM dan English dipaparkan apabila dapat disahkan. Tuding perkataan untuk melihat kawasan asal; tulisan tangan dan angka memerlukan semakan teliti.</p></div><div className="process-card">IMEJ ASAL <ArrowRight size={14}/> JAWI <ArrowRight size={14}/> RUMI <ArrowRight size={14}/> BM MODEN <ArrowRight size={14}/> ENGLISH</div></div>
  {!image?<button className="upload-zone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files[0]);}}><span><Upload size={26}/></span><strong>Muat naik dokumen</strong><small>PNG, JPG, WebP (10 MB) atau PDF (25 MB)</small></button>:<div className="jawi-actions"><div><FileImage size={18}/><strong>{name}{pdfCount?` · muka surat ${pdfPage}/${pdfCount}`:''}</strong></div><div>{pdfCount>1&&<><button className="btn secondary" disabled={pdfPage<=1||loading} onClick={()=>renderPage(pdfPage-1)}>←</button><button className="btn secondary" disabled={pdfPage>=pdfCount||loading} onClick={()=>renderPage(pdfPage+1)}>→</button></>}<button className="btn secondary" onClick={()=>input.current?.click()}>Ganti dokumen</button><button className="btn primary" onClick={analyse} disabled={loading}><ScanSearch size={16}/>{loading?'Memproses…':'Analisis Jawi setempat'}</button></div></div>}
  <input ref={input} type="file" hidden accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e=>pick(e.target.files[0])}/>
  {error&&<div className="notice error" role="alert"><AlertTriangle size={17}/>{error}</div>}
  {lowCoverage&&<div className="notice ocr-warning" role="status"><AlertTriangle size={17}/>OCR mengesan {new Set(result.words.map(word=>word.line)).size} baris dan {result.words.length} kawasan perkataan Jawi. Imej kecil atau kabur menyebabkan banyak huruf tidak pasti, walaupun skor OCR tinggi. Semak bacaan dengan imej asal atau gunakan imbasan beresolusi lebih tinggi.</div>}
  {image&&<div className={'document-workspace'+(lowCoverage?' limited-ocr':'')}><section className="original-card"><header><div><span className="section-kicker">01 / SUMBER</span><h3>Imej asal</h3></div><ZoomIn size={17}/></header><div className="document-image"><img src={image} alt="Dokumen yang dimuat naik"/><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="Kotak perkataan yang dikenal pasti">{result?.words.map(w=><rect key={w.id} x={w.box[0]} y={w.box[1]} width={w.box[2]-w.box[0]} height={w.box[3]-w.box[1]} className={hover.includes(w.id)?'highlight':''} onMouseEnter={()=>hoverIds([w.id])} onMouseLeave={()=>hoverIds([])}/>)}</svg></div><p>Tuding perkataan pada panel sebelah kanan untuk melihat padanan pada imej.</p></section><div className="transcription-grid"><section><span className="section-kicker">02 / TRANSKRIPSI</span><h3>Tulisan asal / Jawi</h3><div lang="ms-Arab" dir="rtl" className="transcription-text original-script">{result?original():<p>Hasil tulisan asal akan dipaparkan di sini.</p>}</div></section><section><span className="section-kicker">03 / TRANSLITERASI</span><h3>Rumi setia</h3><div className="transcription-text">{result?content('rumi'):<p>Padanan huruf Rumi akan dipaparkan di sini.</p>}</div></section><section><span className="section-kicker">04 / NORMALISASI</span><h3>Bahasa Melayu moden</h3><div className="transcription-text">{result?content('bm'):<p>Bahasa Melayu moden akan dipaparkan di sini.</p>}</div></section><section><span className="section-kicker">05 / TERJEMAHAN</span><h3>English</h3><div className="transcription-text">{result?content('en'):<p>The English translation will appear here.</p>}</div></section></div></div>}
  {result&&<div className="document-metadata"><section><span className="section-kicker">06 / ENTITI</span><h3>Nama, tempat & tarikh</h3>{result.entities.length?<div className="entity-list">{result.entities.map((e,i)=><button key={i} onMouseEnter={()=>hoverIds(e.wordIds)} onMouseLeave={()=>hoverIds([])}><small>{e.type}</small>{e.text}</button>)}</div>:<p>Tiada entiti yang dapat dikenal pasti dengan yakin.</p>}</section><section><span className="section-kicker">07 / METADATA</span><h3>Maklumat dokumen</h3><dl><dt>Bahasa</dt><dd>{result.metadata.language}</dd><dt>Tulisan</dt><dd>{result.metadata.script}</dd><dt>Catatan</dt><dd>{result.metadata.notes||'Tiada catatan.'}</dd></dl></section><div className="review-note"><AlertTriangle size={17}/>{lowCoverage?'Bacaan ini ialah draf OCR bagi imej kabur. Skor tinggi juga boleh tersalah baca; semak setiap baris terhadap imej asal.':'Perkataan bergaris titik mempunyai keyakinan OCR rendah. Semak setiap bacaan, terutama tarikh, angka dan tulisan tangan.'}</div></div>}
 </div>;
}
